### ISSUE TITLE
`fibonacci prove` failed

### ISSUE THREAD

**Issue by 3for** [0xPolygonHermez/pil-stark#5]
I'm following [Jordi Baylina's steps](https://www.youtube.com/watch?v=0IZ8-tYaNJM) to try to learn our tool.
1) mkdir tmp
2) fibonacci exec
3) fibonacci PIL verify
4) fibonacci build constree
5) fibonacci prove: get errors as below, how can I fix this? 
```
/usr/local/bin/node --max-old-space-size=32000 src/main_prover.js -m /Users/lanyu/zyd/0xPolygonHermez/pil-stark/tmp/fibonacci.commit -c /Users/lanyu/zyd/0xPolygonHermez/pil-stark/tmp/fibonacci.const -t /Users/lanyu/zyd/0xPolygonHermez/pil-stark/tmp/fibonacci.consttree -p /Users/lanyu/zyd/0xPolygonHermez/pil-stark/test/sm_fibonacci/fibonacci_main.pil -s /Users/lanyu/zyd/0xPolygonHermez/pil-stark/test/sm_fibonacci/fibonacci.starkstruct.json -o /Users/lanyu/zyd/0xPolygonHermez/pil-stark/tmp/fibonacci.proof.json -z /Users/lanyu/zyd/0xPolygonHermez/pil-stark/tmp/fibonacci.proof.zkin.json -b /Users/lanyu/zyd/0xPolygonHermez/pil-stark/tmp/fibonacci.public.json
loading /Users/lanyu/zyd/0xPolygonHermez/pil-stark/tmp/fibonacci.const.. 0 of 0.001953125
loading /Users/lanyu/zyd/0xPolygonHermez/pil-stark/tmp/fibonacci.commit.. 0 of 0.001953125
The "offset" argument must be of type number. Received an instance of Object
TypeError [ERR_INVALID_ARG_TYPE]: The "offset" argument must be of type number. Received an instance of Object
    at read (node:internal/fs/promises:478:5)
    at fsCall (node:internal/fs/promises:313:18)
    at FileHandle.read (node:internal/fs/promises:154:12)
    at MerkleHash.readFromFile (/Users/lanyu/zyd/0xPolygonHermez/pil-stark/src/merklehash_p.js:246:18)
    at async run (/Users/lanyu/zyd/0xPolygonHermez/pil-stark/src/main_prover.js:65:23)
Process exited with code 1
```

**Comment by 3for** [comment]
I upgrade my node from v16 to v18.7.0, then it fixed. 
Better to recommend the node edition in our doc.
